### PR TITLE
 Use dumb-init to correctly forward shutdown signals to gremlin-server 

### PR DESCRIPTION
**Pull request by kristallizer**
Closes bricaud/gremlin-server#6

About dumb-init: https://github.com/Yelp/dumb-init

### CODE REVIEW

**Comment by kristallizer** [comment]
Hey @bricaud can you please review and let me know if you'd like to merge these changes?

**Comment by bricaud** [comment]
Thanks @kristallizer ! 
Sorry I was not responsive, I am jut back from holidays.

Why do you redirect SIGTERM to SIGQUIT ?
I had a quick look but I did not find any doc about which signal to use with the Gremlin server.

**Comment by kristallizer** [comment]
@bricaud thanks! I'm redirecting SIGTERM to SIGINT since that's what gremlin-server is expecting to get to trigger a graceful shutdown.

**Comment by kristallizer** [comment]
@bricaud can you also push the latest build to Docker Hub?

**Comment by bricaud** [comment]
ok it should be available with the "latest" version on Dockerhub.

I got it now for the SIGINT signal, which is equivalent to use ctrl-c to stop the server.
Thanks a lot!

**Comment by kristallizer** [comment]
🚀

**Pull request merged**
